- type: job
  id: na-Baron
  name: job-name-na-baron
  description: job-description-na-baron
  playTimeTracker: Jobna-Baron
  startingGear: BaronGear
  icon: "JobIconQuarterMaster"
#  access:
#  - Harkonnen put this in later

# All of this shits a placeholder. Should have armor set, a weapon, a shield, some food and water
- type: startingGear
  id: na-BaronGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: na-BaronChameleonOutfit
  job: na-Baron
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
