- type: department
  id: HouseAtreides
  name: department-HouseAtreides
  description: department-HouseAtreides-description
  color: "#A46106"
  roles:
  - AtreidesSurvivor

- type: department
  id: TheFremen
  name: department-Fremen
  description: department-Fremen-description
  color: "#9FED58"
  weight: -10
  roles:
  - LisanAlGaib
  - Naib
  - Fremen

- type: department
  id: HouseHarkonnen
  name: department-HouseHarkonnen
  description: department-HouseHarkonnen-description
  color: "#0c344d"
  roles:
  - Baron
  - na-Baron
  - Harkonnen

- type: department
  id: Offworlders
  name: department-Offworlders
  description: department-Offworlders-description
  color: "#334E6D"
  roles:
  - Offworlder
  - Smuggler
