- type: job
  id: AtreidesSurvivor
  name: job-name-atreidessurvivor
  description: job-description-atreidessurvivor
  playTimeTracker: JobAtreidesSurvivor
  startingGear: AtreidesSurvivorGear
  icon: "JobIconQuarterMaster"
#  access:
#  - Atreides put this in later

# All of this shits a placeholder. Should have armor set, a weapon, a shield, some food and water
- type: startingGear
  id: AtreidesSurvivorGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: AtreidesSurvivorChameleonOutfit
  job: AtreidesSurvivor
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
