- type: job
  id: Fremen
  name: job-name-fremen
  description: job-description-fremen
  playTimeTracker: JobFremen
  startingGear: FremenGear
  icon: "JobIconQuarterMaster"
#  access:
#  - Fremen put this in later

# All of this shits a placeholder. Should have armor set, a weapon, some food and water
- type: startingGear
  id: FremenGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: FremenChameleonOutfit
  job: Fremen
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
