- type: job
  id: LisanAlGhaib
  name: job-name-lisanalghaib
  description: job-description-lisanalghaib
  playTimeTracker: JobLisanAlGhaib
  startingGear: LisanAlGhaibGear
  icon: "JobIconQuarterMaster"
#  access:
#  - Fremen put this in later

# All of this shits a placeholder. Should have armor set, a weapon, some food and water
- type: startingGear
  id: LisanAlGhaibGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: LisanAlGhaibChameleonOutfit
  job: LisanAlGhaib
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
